---
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: mkosi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: systemd/mkosi@v24.3

      - name: configure 
        run: |
           cp postinst.chroot /opt 
           mkosi dependencies
           apt-get update 
           apt-get install -y systemd-ukify systemd-repart
      
      - name: build image 
        run: mkosi build
