---
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: mkosi
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
      - uses: systemd/mkosi@v24.3

      - name: configure 
        run: cp postinst.chroot /opt 

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y systemd-ukify systemd-boot systemd-repart
      
      - name: build image 
        run: mkosi build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: sid-usi.efi
          path: ~/**/**/**/sid-usi.efi
          if-no-files-found: error
