---
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: mkosi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: systemd/mkosi@v24.3
      - run: |
           cp postinst.chroot /opt 
           mkosi -I mkosi.conf
